# permissions for end users to view shutdownschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shutdownscheduler-viewer-role
rules:
- apiGroups:
  - wildlife.io
  resources:
  - shutdownschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wildlife.io
  resources:
  - shutdownschedulers/status
  verbs:
  - get
