apiVersion: wildlife.io/v1alpha1
kind: ShutdownScheduler
metadata:
  name: test
  namespace: shutdown-scheduler
spec:
  resource:
    apiVersion: v1
    kind: Deploy
    name: debug
    namespace: hackathon28-shutdown-scheduler
  timeRange:
  - start: "2022-06-23T20:29:49-03:00"
    end:  "2022-06-23T02:29:49-03:00"
  
    